// source: rcp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.AlterarFaltasReq', null, global);
goog.exportSymbol('proto.AlterarNotaReq', null, global);
goog.exportSymbol('proto.Aluno', null, global);
goog.exportSymbol('proto.AlunosReq', null, global);
goog.exportSymbol('proto.AlunosRes', null, global);
goog.exportSymbol('proto.DisciplinasReq', null, global);
goog.exportSymbol('proto.DisciplinasRes', null, global);
goog.exportSymbol('proto.InserirMatriculaRes', null, global);
goog.exportSymbol('proto.ListaDisciplina', null, global);
goog.exportSymbol('proto.Matricula', null, global);
goog.exportSymbol('proto.MessageRes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ListaDisciplina = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ListaDisciplina, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ListaDisciplina.displayName = 'proto.ListaDisciplina';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DisciplinasReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DisciplinasReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DisciplinasReq.displayName = 'proto.DisciplinasReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DisciplinasRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DisciplinasRes.repeatedFields_, null);
};
goog.inherits(proto.DisciplinasRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DisciplinasRes.displayName = 'proto.DisciplinasRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MessageRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MessageRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MessageRes.displayName = 'proto.MessageRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AlterarNotaReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AlterarNotaReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AlterarNotaReq.displayName = 'proto.AlterarNotaReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AlterarFaltasReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AlterarFaltasReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AlterarFaltasReq.displayName = 'proto.AlterarFaltasReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Matricula = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Matricula, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Matricula.displayName = 'proto.Matricula';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.InserirMatriculaRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.InserirMatriculaRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.InserirMatriculaRes.displayName = 'proto.InserirMatriculaRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AlunosReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AlunosReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AlunosReq.displayName = 'proto.AlunosReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AlunosRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AlunosRes.repeatedFields_, null);
};
goog.inherits(proto.AlunosRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AlunosRes.displayName = 'proto.AlunosRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Aluno = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Aluno, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Aluno.displayName = 'proto.Aluno';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ListaDisciplina.prototype.toObject = function(opt_includeInstance) {
  return proto.ListaDisciplina.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ListaDisciplina} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ListaDisciplina.toObject = function(includeInstance, msg) {
  var f, obj = {
    ra: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nome: jspb.Message.getFieldWithDefault(msg, 2, ""),
    nota: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    faltas: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ListaDisciplina}
 */
proto.ListaDisciplina.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ListaDisciplina;
  return proto.ListaDisciplina.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ListaDisciplina} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ListaDisciplina}
 */
proto.ListaDisciplina.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRa(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNome(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setNota(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFaltas(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ListaDisciplina.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ListaDisciplina.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ListaDisciplina} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ListaDisciplina.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRa();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNome();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNota();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getFaltas();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional int32 RA = 1;
 * @return {number}
 */
proto.ListaDisciplina.prototype.getRa = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ListaDisciplina} returns this
 */
proto.ListaDisciplina.prototype.setRa = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string nome = 2;
 * @return {string}
 */
proto.ListaDisciplina.prototype.getNome = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ListaDisciplina} returns this
 */
proto.ListaDisciplina.prototype.setNome = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float nota = 3;
 * @return {number}
 */
proto.ListaDisciplina.prototype.getNota = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ListaDisciplina} returns this
 */
proto.ListaDisciplina.prototype.setNota = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 faltas = 4;
 * @return {number}
 */
proto.ListaDisciplina.prototype.getFaltas = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ListaDisciplina} returns this
 */
proto.ListaDisciplina.prototype.setFaltas = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DisciplinasReq.prototype.toObject = function(opt_includeInstance) {
  return proto.DisciplinasReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DisciplinasReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DisciplinasReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    ano: jspb.Message.getFieldWithDefault(msg, 1, 0),
    semestre: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DisciplinasReq}
 */
proto.DisciplinasReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DisciplinasReq;
  return proto.DisciplinasReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DisciplinasReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DisciplinasReq}
 */
proto.DisciplinasReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAno(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSemestre(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DisciplinasReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DisciplinasReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DisciplinasReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DisciplinasReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAno();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSemestre();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 ano = 1;
 * @return {number}
 */
proto.DisciplinasReq.prototype.getAno = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.DisciplinasReq} returns this
 */
proto.DisciplinasReq.prototype.setAno = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 semestre = 2;
 * @return {number}
 */
proto.DisciplinasReq.prototype.getSemestre = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.DisciplinasReq} returns this
 */
proto.DisciplinasReq.prototype.setSemestre = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DisciplinasRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DisciplinasRes.prototype.toObject = function(opt_includeInstance) {
  return proto.DisciplinasRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DisciplinasRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DisciplinasRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    disciplinasList: jspb.Message.toObjectList(msg.getDisciplinasList(),
    proto.ListaDisciplina.toObject, includeInstance),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DisciplinasRes}
 */
proto.DisciplinasRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DisciplinasRes;
  return proto.DisciplinasRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DisciplinasRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DisciplinasRes}
 */
proto.DisciplinasRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ListaDisciplina;
      reader.readMessage(value,proto.ListaDisciplina.deserializeBinaryFromReader);
      msg.addDisciplinas(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DisciplinasRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DisciplinasRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DisciplinasRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DisciplinasRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDisciplinasList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.ListaDisciplina.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated ListaDisciplina disciplinas = 1;
 * @return {!Array<!proto.ListaDisciplina>}
 */
proto.DisciplinasRes.prototype.getDisciplinasList = function() {
  return /** @type{!Array<!proto.ListaDisciplina>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ListaDisciplina, 1));
};


/**
 * @param {!Array<!proto.ListaDisciplina>} value
 * @return {!proto.DisciplinasRes} returns this
*/
proto.DisciplinasRes.prototype.setDisciplinasList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ListaDisciplina=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ListaDisciplina}
 */
proto.DisciplinasRes.prototype.addDisciplinas = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ListaDisciplina, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.DisciplinasRes} returns this
 */
proto.DisciplinasRes.prototype.clearDisciplinasList = function() {
  return this.setDisciplinasList([]);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.DisciplinasRes.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.DisciplinasRes} returns this
 */
proto.DisciplinasRes.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MessageRes.prototype.toObject = function(opt_includeInstance) {
  return proto.MessageRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MessageRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MessageRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MessageRes}
 */
proto.MessageRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MessageRes;
  return proto.MessageRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MessageRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MessageRes}
 */
proto.MessageRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MessageRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MessageRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MessageRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MessageRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.MessageRes.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MessageRes} returns this
 */
proto.MessageRes.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AlterarNotaReq.prototype.toObject = function(opt_includeInstance) {
  return proto.AlterarNotaReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AlterarNotaReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlterarNotaReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    ra: jspb.Message.getFieldWithDefault(msg, 1, 0),
    codDisciplina: jspb.Message.getFieldWithDefault(msg, 2, ""),
    nota: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AlterarNotaReq}
 */
proto.AlterarNotaReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AlterarNotaReq;
  return proto.AlterarNotaReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AlterarNotaReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AlterarNotaReq}
 */
proto.AlterarNotaReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRa(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodDisciplina(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setNota(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AlterarNotaReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AlterarNotaReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AlterarNotaReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlterarNotaReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRa();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCodDisciplina();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNota();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * optional int32 RA = 1;
 * @return {number}
 */
proto.AlterarNotaReq.prototype.getRa = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.AlterarNotaReq} returns this
 */
proto.AlterarNotaReq.prototype.setRa = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string cod_disciplina = 2;
 * @return {string}
 */
proto.AlterarNotaReq.prototype.getCodDisciplina = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.AlterarNotaReq} returns this
 */
proto.AlterarNotaReq.prototype.setCodDisciplina = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float nota = 3;
 * @return {number}
 */
proto.AlterarNotaReq.prototype.getNota = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.AlterarNotaReq} returns this
 */
proto.AlterarNotaReq.prototype.setNota = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AlterarFaltasReq.prototype.toObject = function(opt_includeInstance) {
  return proto.AlterarFaltasReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AlterarFaltasReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlterarFaltasReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    ra: jspb.Message.getFieldWithDefault(msg, 1, 0),
    codDisciplina: jspb.Message.getFieldWithDefault(msg, 2, ""),
    faltas: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AlterarFaltasReq}
 */
proto.AlterarFaltasReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AlterarFaltasReq;
  return proto.AlterarFaltasReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AlterarFaltasReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AlterarFaltasReq}
 */
proto.AlterarFaltasReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRa(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodDisciplina(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFaltas(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AlterarFaltasReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AlterarFaltasReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AlterarFaltasReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlterarFaltasReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRa();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCodDisciplina();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFaltas();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 RA = 1;
 * @return {number}
 */
proto.AlterarFaltasReq.prototype.getRa = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.AlterarFaltasReq} returns this
 */
proto.AlterarFaltasReq.prototype.setRa = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string cod_disciplina = 2;
 * @return {string}
 */
proto.AlterarFaltasReq.prototype.getCodDisciplina = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.AlterarFaltasReq} returns this
 */
proto.AlterarFaltasReq.prototype.setCodDisciplina = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 faltas = 3;
 * @return {number}
 */
proto.AlterarFaltasReq.prototype.getFaltas = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.AlterarFaltasReq} returns this
 */
proto.AlterarFaltasReq.prototype.setFaltas = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Matricula.prototype.toObject = function(opt_includeInstance) {
  return proto.Matricula.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Matricula} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Matricula.toObject = function(includeInstance, msg) {
  var f, obj = {
    ra: jspb.Message.getFieldWithDefault(msg, 1, 0),
    codDisciplina: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ano: jspb.Message.getFieldWithDefault(msg, 3, 0),
    semestre: jspb.Message.getFieldWithDefault(msg, 4, 0),
    nota: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    faltas: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Matricula}
 */
proto.Matricula.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Matricula;
  return proto.Matricula.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Matricula} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Matricula}
 */
proto.Matricula.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRa(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodDisciplina(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAno(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSemestre(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setNota(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFaltas(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Matricula.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Matricula.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Matricula} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Matricula.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRa();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCodDisciplina();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAno();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSemestre();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getNota();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getFaltas();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional int32 RA = 1;
 * @return {number}
 */
proto.Matricula.prototype.getRa = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Matricula} returns this
 */
proto.Matricula.prototype.setRa = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string cod_disciplina = 2;
 * @return {string}
 */
proto.Matricula.prototype.getCodDisciplina = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Matricula} returns this
 */
proto.Matricula.prototype.setCodDisciplina = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 ano = 3;
 * @return {number}
 */
proto.Matricula.prototype.getAno = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Matricula} returns this
 */
proto.Matricula.prototype.setAno = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 semestre = 4;
 * @return {number}
 */
proto.Matricula.prototype.getSemestre = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Matricula} returns this
 */
proto.Matricula.prototype.setSemestre = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional float nota = 5;
 * @return {number}
 */
proto.Matricula.prototype.getNota = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Matricula} returns this
 */
proto.Matricula.prototype.setNota = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional int32 faltas = 6;
 * @return {number}
 */
proto.Matricula.prototype.getFaltas = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.Matricula} returns this
 */
proto.Matricula.prototype.setFaltas = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.InserirMatriculaRes.prototype.toObject = function(opt_includeInstance) {
  return proto.InserirMatriculaRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.InserirMatriculaRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.InserirMatriculaRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    matricula: (f = msg.getMatricula()) && proto.Matricula.toObject(includeInstance, f),
    message: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.InserirMatriculaRes}
 */
proto.InserirMatriculaRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.InserirMatriculaRes;
  return proto.InserirMatriculaRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.InserirMatriculaRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.InserirMatriculaRes}
 */
proto.InserirMatriculaRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.Matricula;
      reader.readMessage(value,proto.Matricula.deserializeBinaryFromReader);
      msg.setMatricula(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.InserirMatriculaRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.InserirMatriculaRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.InserirMatriculaRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.InserirMatriculaRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMatricula();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Matricula.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Matricula matricula = 2;
 * @return {?proto.Matricula}
 */
proto.InserirMatriculaRes.prototype.getMatricula = function() {
  return /** @type{?proto.Matricula} */ (
    jspb.Message.getWrapperField(this, proto.Matricula, 2));
};


/**
 * @param {?proto.Matricula|undefined} value
 * @return {!proto.InserirMatriculaRes} returns this
*/
proto.InserirMatriculaRes.prototype.setMatricula = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.InserirMatriculaRes} returns this
 */
proto.InserirMatriculaRes.prototype.clearMatricula = function() {
  return this.setMatricula(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.InserirMatriculaRes.prototype.hasMatricula = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.InserirMatriculaRes.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.InserirMatriculaRes} returns this
 */
proto.InserirMatriculaRes.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AlunosReq.prototype.toObject = function(opt_includeInstance) {
  return proto.AlunosReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AlunosReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlunosReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    codDisciplina: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ano: jspb.Message.getFieldWithDefault(msg, 2, 0),
    semestre: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AlunosReq}
 */
proto.AlunosReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AlunosReq;
  return proto.AlunosReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AlunosReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AlunosReq}
 */
proto.AlunosReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodDisciplina(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAno(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSemestre(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AlunosReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AlunosReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AlunosReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlunosReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCodDisciplina();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAno();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSemestre();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string cod_disciplina = 1;
 * @return {string}
 */
proto.AlunosReq.prototype.getCodDisciplina = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.AlunosReq} returns this
 */
proto.AlunosReq.prototype.setCodDisciplina = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 ano = 2;
 * @return {number}
 */
proto.AlunosReq.prototype.getAno = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.AlunosReq} returns this
 */
proto.AlunosReq.prototype.setAno = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 semestre = 3;
 * @return {number}
 */
proto.AlunosReq.prototype.getSemestre = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.AlunosReq} returns this
 */
proto.AlunosReq.prototype.setSemestre = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AlunosRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AlunosRes.prototype.toObject = function(opt_includeInstance) {
  return proto.AlunosRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AlunosRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlunosRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    alunosList: jspb.Message.toObjectList(msg.getAlunosList(),
    proto.Aluno.toObject, includeInstance),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AlunosRes}
 */
proto.AlunosRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AlunosRes;
  return proto.AlunosRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AlunosRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AlunosRes}
 */
proto.AlunosRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Aluno;
      reader.readMessage(value,proto.Aluno.deserializeBinaryFromReader);
      msg.addAlunos(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AlunosRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AlunosRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AlunosRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AlunosRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlunosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Aluno.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated Aluno alunos = 1;
 * @return {!Array<!proto.Aluno>}
 */
proto.AlunosRes.prototype.getAlunosList = function() {
  return /** @type{!Array<!proto.Aluno>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Aluno, 1));
};


/**
 * @param {!Array<!proto.Aluno>} value
 * @return {!proto.AlunosRes} returns this
*/
proto.AlunosRes.prototype.setAlunosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Aluno=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Aluno}
 */
proto.AlunosRes.prototype.addAlunos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Aluno, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AlunosRes} returns this
 */
proto.AlunosRes.prototype.clearAlunosList = function() {
  return this.setAlunosList([]);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.AlunosRes.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.AlunosRes} returns this
 */
proto.AlunosRes.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Aluno.prototype.toObject = function(opt_includeInstance) {
  return proto.Aluno.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Aluno} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Aluno.toObject = function(includeInstance, msg) {
  var f, obj = {
    ra: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nome: jspb.Message.getFieldWithDefault(msg, 2, ""),
    periodo: jspb.Message.getFieldWithDefault(msg, 3, 0),
    codCurso: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Aluno}
 */
proto.Aluno.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Aluno;
  return proto.Aluno.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Aluno} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Aluno}
 */
proto.Aluno.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRa(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNome(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPeriodo(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCodCurso(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Aluno.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Aluno.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Aluno} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Aluno.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRa();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNome();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPeriodo();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getCodCurso();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional int32 RA = 1;
 * @return {number}
 */
proto.Aluno.prototype.getRa = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Aluno} returns this
 */
proto.Aluno.prototype.setRa = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string nome = 2;
 * @return {string}
 */
proto.Aluno.prototype.getNome = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Aluno} returns this
 */
proto.Aluno.prototype.setNome = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 periodo = 3;
 * @return {number}
 */
proto.Aluno.prototype.getPeriodo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Aluno} returns this
 */
proto.Aluno.prototype.setPeriodo = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 cod_curso = 4;
 * @return {number}
 */
proto.Aluno.prototype.getCodCurso = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Aluno} returns this
 */
proto.Aluno.prototype.setCodCurso = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto);
