<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alunos.proto

namespace App\Proto\GPBMetadata;

class Alunos
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
µ
alunos.proto"E
Aluno

RA (
nome (	
periodo (
	cod_curso ("0
	CrudAluno
type (
aluno (2.AlunoB$Ê	App\\ProtoâApp\\Proto\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

