<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cursos.proto

namespace App\Proto\GPBMetadata;

class Cursos
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
•
cursos.proto"%
Curso
codigo (	
nome (	"0
	CrudCurso
type (
curso (2.CursoB$Ê	App\\ProtoâApp\\Proto\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

