<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matriculas.proto

namespace App\Proto\GPBMetadata;

class Matriculas
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ì
matriculas.proto"l
	Matricula

RA (
cod_disciplina (	
ano (
semestre (
nota (
faltas ("<
CrudMatricula
type (
	matricula (2
.MatriculaB$Ê	App\\ProtoâApp\\Proto\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

