<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alunos.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Aluno</code>
 */
class Aluno extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 RA = 1;</code>
     */
    protected $RA = 0;
    /**
     * Generated from protobuf field <code>string nome = 2;</code>
     */
    protected $nome = '';
    /**
     * Generated from protobuf field <code>int32 periodo = 3;</code>
     */
    protected $periodo = 0;
    /**
     * Generated from protobuf field <code>int32 cod_curso = 4;</code>
     */
    protected $cod_curso = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $RA
     *     @type string $nome
     *     @type int $periodo
     *     @type int $cod_curso
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\Alunos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 RA = 1;</code>
     * @return int
     */
    public function getRA()
    {
        return $this->RA;
    }

    /**
     * Generated from protobuf field <code>int32 RA = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRA($var)
    {
        GPBUtil::checkInt32($var);
        $this->RA = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nome = 2;</code>
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * Generated from protobuf field <code>string nome = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNome($var)
    {
        GPBUtil::checkString($var, True);
        $this->nome = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 periodo = 3;</code>
     * @return int
     */
    public function getPeriodo()
    {
        return $this->periodo;
    }

    /**
     * Generated from protobuf field <code>int32 periodo = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPeriodo($var)
    {
        GPBUtil::checkInt32($var);
        $this->periodo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cod_curso = 4;</code>
     * @return int
     */
    public function getCodCurso()
    {
        return $this->cod_curso;
    }

    /**
     * Generated from protobuf field <code>int32 cod_curso = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCodCurso($var)
    {
        GPBUtil::checkInt32($var);
        $this->cod_curso = $var;

        return $this;
    }

}

