<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matriculas.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CrudMatricula</code>
 */
class CrudMatricula extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>.Matricula matricula = 2;</code>
     */
    protected $matricula = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \App\Proto\Matricula $matricula
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\Matriculas::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Matricula matricula = 2;</code>
     * @return \App\Proto\Matricula|null
     */
    public function getMatricula()
    {
        return $this->matricula;
    }

    public function hasMatricula()
    {
        return isset($this->matricula);
    }

    public function clearMatricula()
    {
        unset($this->matricula);
    }

    /**
     * Generated from protobuf field <code>.Matricula matricula = 2;</code>
     * @param \App\Proto\Matricula $var
     * @return $this
     */
    public function setMatricula($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\Matricula::class);
        $this->matricula = $var;

        return $this;
    }

}

