<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cursos.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CrudCurso</code>
 */
class CrudCurso extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>.Curso curso = 2;</code>
     */
    protected $curso = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \App\Proto\Curso $curso
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\Cursos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Curso curso = 2;</code>
     * @return \App\Proto\Curso|null
     */
    public function getCurso()
    {
        return $this->curso;
    }

    public function hasCurso()
    {
        return isset($this->curso);
    }

    public function clearCurso()
    {
        unset($this->curso);
    }

    /**
     * Generated from protobuf field <code>.Curso curso = 2;</code>
     * @param \App\Proto\Curso $var
     * @return $this
     */
    public function setCurso($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\Curso::class);
        $this->curso = $var;

        return $this;
    }

}

