<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alunos.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CrudAluno</code>
 */
class CrudAluno extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>.Aluno aluno = 2;</code>
     */
    protected $aluno = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \App\Proto\Aluno $aluno
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\Alunos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Aluno aluno = 2;</code>
     * @return \App\Proto\Aluno|null
     */
    public function getAluno()
    {
        return $this->aluno;
    }

    public function hasAluno()
    {
        return isset($this->aluno);
    }

    public function clearAluno()
    {
        unset($this->aluno);
    }

    /**
     * Generated from protobuf field <code>.Aluno aluno = 2;</code>
     * @param \App\Proto\Aluno $var
     * @return $this
     */
    public function setAluno($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\Aluno::class);
        $this->aluno = $var;

        return $this;
    }

}

