<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: disciplinas.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Disciplina</code>
 */
class Disciplina extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string codigo = 1;</code>
     */
    protected $codigo = '';
    /**
     * Generated from protobuf field <code>string nome = 2;</code>
     */
    protected $nome = '';
    /**
     * Generated from protobuf field <code>string professor = 3;</code>
     */
    protected $professor = '';
    /**
     * Generated from protobuf field <code>int32 cod_curso = 4;</code>
     */
    protected $cod_curso = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $codigo
     *     @type string $nome
     *     @type string $professor
     *     @type int $cod_curso
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\Disciplinas::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string codigo = 1;</code>
     * @return string
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * Generated from protobuf field <code>string codigo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCodigo($var)
    {
        GPBUtil::checkString($var, True);
        $this->codigo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nome = 2;</code>
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * Generated from protobuf field <code>string nome = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNome($var)
    {
        GPBUtil::checkString($var, True);
        $this->nome = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string professor = 3;</code>
     * @return string
     */
    public function getProfessor()
    {
        return $this->professor;
    }

    /**
     * Generated from protobuf field <code>string professor = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProfessor($var)
    {
        GPBUtil::checkString($var, True);
        $this->professor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cod_curso = 4;</code>
     * @return int
     */
    public function getCodCurso()
    {
        return $this->cod_curso;
    }

    /**
     * Generated from protobuf field <code>int32 cod_curso = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCodCurso($var)
    {
        GPBUtil::checkInt32($var);
        $this->cod_curso = $var;

        return $this;
    }

}

