<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matriculas.proto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Matricula</code>
 */
class Matricula extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 RA = 1;</code>
     */
    protected $RA = 0;
    /**
     * Generated from protobuf field <code>string cod_disciplina = 2;</code>
     */
    protected $cod_disciplina = '';
    /**
     * Generated from protobuf field <code>int32 ano = 3;</code>
     */
    protected $ano = 0;
    /**
     * Generated from protobuf field <code>int32 semestre = 4;</code>
     */
    protected $semestre = 0;
    /**
     * Generated from protobuf field <code>float nota = 5;</code>
     */
    protected $nota = 0.0;
    /**
     * Generated from protobuf field <code>int32 faltas = 6;</code>
     */
    protected $faltas = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $RA
     *     @type string $cod_disciplina
     *     @type int $ano
     *     @type int $semestre
     *     @type float $nota
     *     @type int $faltas
     * }
     */
    public function __construct($data = NULL) {
        \App\Proto\GPBMetadata\Matriculas::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 RA = 1;</code>
     * @return int
     */
    public function getRA()
    {
        return $this->RA;
    }

    /**
     * Generated from protobuf field <code>int32 RA = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRA($var)
    {
        GPBUtil::checkInt32($var);
        $this->RA = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cod_disciplina = 2;</code>
     * @return string
     */
    public function getCodDisciplina()
    {
        return $this->cod_disciplina;
    }

    /**
     * Generated from protobuf field <code>string cod_disciplina = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCodDisciplina($var)
    {
        GPBUtil::checkString($var, True);
        $this->cod_disciplina = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ano = 3;</code>
     * @return int
     */
    public function getAno()
    {
        return $this->ano;
    }

    /**
     * Generated from protobuf field <code>int32 ano = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAno($var)
    {
        GPBUtil::checkInt32($var);
        $this->ano = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 semestre = 4;</code>
     * @return int
     */
    public function getSemestre()
    {
        return $this->semestre;
    }

    /**
     * Generated from protobuf field <code>int32 semestre = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSemestre($var)
    {
        GPBUtil::checkInt32($var);
        $this->semestre = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float nota = 5;</code>
     * @return float
     */
    public function getNota()
    {
        return $this->nota;
    }

    /**
     * Generated from protobuf field <code>float nota = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setNota($var)
    {
        GPBUtil::checkFloat($var);
        $this->nota = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 faltas = 6;</code>
     * @return int
     */
    public function getFaltas()
    {
        return $this->faltas;
    }

    /**
     * Generated from protobuf field <code>int32 faltas = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setFaltas($var)
    {
        GPBUtil::checkInt32($var);
        $this->faltas = $var;

        return $this;
    }

}

