# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rcp_pb2 as rcp__pb2


class ServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InserirMatricula = channel.unary_unary(
                '/Services/InserirMatricula',
                request_serializer=rcp__pb2.Matricula.SerializeToString,
                response_deserializer=rcp__pb2.CrudMatricula.FromString,
                )
        self.AlterarMatricula = channel.unary_unary(
                '/Services/AlterarMatricula',
                request_serializer=rcp__pb2.Matricula.SerializeToString,
                response_deserializer=rcp__pb2.CrudMatricula.FromString,
                )
        self.ListarDisciplinas = channel.unary_unary(
                '/Services/ListarDisciplinas',
                request_serializer=rcp__pb2.Matricula.SerializeToString,
                response_deserializer=rcp__pb2.CrudMatricula.FromString,
                )
        self.ListarAlunos = channel.unary_unary(
                '/Services/ListarAlunos',
                request_serializer=rcp__pb2.AlunosReq.SerializeToString,
                response_deserializer=rcp__pb2.AlunosRes.FromString,
                )


class ServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InserirMatricula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterarMatricula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarDisciplinas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarAlunos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InserirMatricula': grpc.unary_unary_rpc_method_handler(
                    servicer.InserirMatricula,
                    request_deserializer=rcp__pb2.Matricula.FromString,
                    response_serializer=rcp__pb2.CrudMatricula.SerializeToString,
            ),
            'AlterarMatricula': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterarMatricula,
                    request_deserializer=rcp__pb2.Matricula.FromString,
                    response_serializer=rcp__pb2.CrudMatricula.SerializeToString,
            ),
            'ListarDisciplinas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarDisciplinas,
                    request_deserializer=rcp__pb2.Matricula.FromString,
                    response_serializer=rcp__pb2.CrudMatricula.SerializeToString,
            ),
            'ListarAlunos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarAlunos,
                    request_deserializer=rcp__pb2.AlunosReq.FromString,
                    response_serializer=rcp__pb2.AlunosRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Services', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Services(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InserirMatricula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/InserirMatricula',
            rcp__pb2.Matricula.SerializeToString,
            rcp__pb2.CrudMatricula.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlterarMatricula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/AlterarMatricula',
            rcp__pb2.Matricula.SerializeToString,
            rcp__pb2.CrudMatricula.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarDisciplinas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/ListarDisciplinas',
            rcp__pb2.Matricula.SerializeToString,
            rcp__pb2.CrudMatricula.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarAlunos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/ListarAlunos',
            rcp__pb2.AlunosReq.SerializeToString,
            rcp__pb2.AlunosRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
