# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rcp_pb2 as proto_dot_rcp__pb2


class ServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InserirMatricula = channel.unary_unary(
                '/Services/InserirMatricula',
                request_serializer=proto_dot_rcp__pb2.Matricula.SerializeToString,
                response_deserializer=proto_dot_rcp__pb2.InserirMatriculaRes.FromString,
                )
        self.AlterarNota = channel.unary_unary(
                '/Services/AlterarNota',
                request_serializer=proto_dot_rcp__pb2.AlterarNotaReq.SerializeToString,
                response_deserializer=proto_dot_rcp__pb2.MessageRes.FromString,
                )
        self.AlterarFaltas = channel.unary_unary(
                '/Services/AlterarFaltas',
                request_serializer=proto_dot_rcp__pb2.AlterarFaltasReq.SerializeToString,
                response_deserializer=proto_dot_rcp__pb2.MessageRes.FromString,
                )
        self.ListarDisciplinas = channel.unary_unary(
                '/Services/ListarDisciplinas',
                request_serializer=proto_dot_rcp__pb2.DisciplinasReq.SerializeToString,
                response_deserializer=proto_dot_rcp__pb2.DisciplinasRes.FromString,
                )
        self.ListarAlunos = channel.unary_unary(
                '/Services/ListarAlunos',
                request_serializer=proto_dot_rcp__pb2.AlunosReq.SerializeToString,
                response_deserializer=proto_dot_rcp__pb2.AlunosRes.FromString,
                )


class ServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InserirMatricula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterarNota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterarFaltas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarDisciplinas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarAlunos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InserirMatricula': grpc.unary_unary_rpc_method_handler(
                    servicer.InserirMatricula,
                    request_deserializer=proto_dot_rcp__pb2.Matricula.FromString,
                    response_serializer=proto_dot_rcp__pb2.InserirMatriculaRes.SerializeToString,
            ),
            'AlterarNota': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterarNota,
                    request_deserializer=proto_dot_rcp__pb2.AlterarNotaReq.FromString,
                    response_serializer=proto_dot_rcp__pb2.MessageRes.SerializeToString,
            ),
            'AlterarFaltas': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterarFaltas,
                    request_deserializer=proto_dot_rcp__pb2.AlterarFaltasReq.FromString,
                    response_serializer=proto_dot_rcp__pb2.MessageRes.SerializeToString,
            ),
            'ListarDisciplinas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarDisciplinas,
                    request_deserializer=proto_dot_rcp__pb2.DisciplinasReq.FromString,
                    response_serializer=proto_dot_rcp__pb2.DisciplinasRes.SerializeToString,
            ),
            'ListarAlunos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarAlunos,
                    request_deserializer=proto_dot_rcp__pb2.AlunosReq.FromString,
                    response_serializer=proto_dot_rcp__pb2.AlunosRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Services', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Services(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InserirMatricula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/InserirMatricula',
            proto_dot_rcp__pb2.Matricula.SerializeToString,
            proto_dot_rcp__pb2.InserirMatriculaRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlterarNota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/AlterarNota',
            proto_dot_rcp__pb2.AlterarNotaReq.SerializeToString,
            proto_dot_rcp__pb2.MessageRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlterarFaltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/AlterarFaltas',
            proto_dot_rcp__pb2.AlterarFaltasReq.SerializeToString,
            proto_dot_rcp__pb2.MessageRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarDisciplinas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/ListarDisciplinas',
            proto_dot_rcp__pb2.DisciplinasReq.SerializeToString,
            proto_dot_rcp__pb2.DisciplinasRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarAlunos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/ListarAlunos',
            proto_dot_rcp__pb2.AlunosReq.SerializeToString,
            proto_dot_rcp__pb2.AlunosRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
