# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rcp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trcp.proto\"l\n\tMatricula\x12\n\n\x02RA\x18\x01 \x01(\x05\x12\x16\n\x0e\x63od_disciplina\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\x12\x10\n\x08semestre\x18\x04 \x01(\x05\x12\x0c\n\x04nota\x18\x05 \x01(\x02\x12\x0e\n\x06\x66\x61ltas\x18\x06 \x01(\x05\"M\n\rCrudMatricula\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x1d\n\tmatricula\x18\x02 \x01(\x0b\x32\n.Matricula\x12\x0f\n\x07message\x18\x03 \x01(\t\"P\n\nDisciplina\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tprofessor\x18\x03 \x01(\t\x12\x11\n\tcod_curso\x18\x04 \x01(\x05\"?\n\x0e\x43rudDisciplina\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x1f\n\ndisciplina\x18\x02 \x01(\x0b\x32\x0b.Disciplina\"%\n\x05\x43urso\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\"0\n\tCrudCurso\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x15\n\x05\x63urso\x18\x02 \x01(\x0b\x32\x06.Curso\"E\n\x05\x41luno\x12\n\n\x02RA\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07periodo\x18\x03 \x01(\x05\x12\x11\n\tcod_curso\x18\x04 \x01(\x05\"0\n\tCrudAluno\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x15\n\x05\x61luno\x18\x02 \x01(\x0b\x32\x06.Aluno\"B\n\tAlunosReq\x12\x16\n\x0e\x63od_disciplina\x18\x01 \x01(\t\x12\x0b\n\x03\x61no\x18\x02 \x01(\x05\x12\x10\n\x08semestre\x18\x03 \x01(\x05\"4\n\tAlunosRes\x12\x16\n\x06\x61lunos\x18\x01 \x03(\x0b\x32\x06.Aluno\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcb\x01\n\x08Services\x12\x30\n\x10InserirMatricula\x12\n.Matricula\x1a\x0e.CrudMatricula\"\x00\x12\x30\n\x10\x41lterarMatricula\x12\n.Matricula\x1a\x0e.CrudMatricula\"\x00\x12\x31\n\x11ListarDisciplinas\x12\n.Matricula\x1a\x0e.CrudMatricula\"\x00\x12(\n\x0cListarAlunos\x12\n.AlunosReq\x1a\n.AlunosRes\"\x00\x42$\xca\x02\tApp\\Proto\xe2\x02\x15\x41pp\\Proto\\GPBMetadatab\x06proto3')



_MATRICULA = DESCRIPTOR.message_types_by_name['Matricula']
_CRUDMATRICULA = DESCRIPTOR.message_types_by_name['CrudMatricula']
_DISCIPLINA = DESCRIPTOR.message_types_by_name['Disciplina']
_CRUDDISCIPLINA = DESCRIPTOR.message_types_by_name['CrudDisciplina']
_CURSO = DESCRIPTOR.message_types_by_name['Curso']
_CRUDCURSO = DESCRIPTOR.message_types_by_name['CrudCurso']
_ALUNO = DESCRIPTOR.message_types_by_name['Aluno']
_CRUDALUNO = DESCRIPTOR.message_types_by_name['CrudAluno']
_ALUNOSREQ = DESCRIPTOR.message_types_by_name['AlunosReq']
_ALUNOSRES = DESCRIPTOR.message_types_by_name['AlunosRes']
Matricula = _reflection.GeneratedProtocolMessageType('Matricula', (_message.Message,), {
  'DESCRIPTOR' : _MATRICULA,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:Matricula)
  })
_sym_db.RegisterMessage(Matricula)

CrudMatricula = _reflection.GeneratedProtocolMessageType('CrudMatricula', (_message.Message,), {
  'DESCRIPTOR' : _CRUDMATRICULA,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:CrudMatricula)
  })
_sym_db.RegisterMessage(CrudMatricula)

Disciplina = _reflection.GeneratedProtocolMessageType('Disciplina', (_message.Message,), {
  'DESCRIPTOR' : _DISCIPLINA,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:Disciplina)
  })
_sym_db.RegisterMessage(Disciplina)

CrudDisciplina = _reflection.GeneratedProtocolMessageType('CrudDisciplina', (_message.Message,), {
  'DESCRIPTOR' : _CRUDDISCIPLINA,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:CrudDisciplina)
  })
_sym_db.RegisterMessage(CrudDisciplina)

Curso = _reflection.GeneratedProtocolMessageType('Curso', (_message.Message,), {
  'DESCRIPTOR' : _CURSO,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:Curso)
  })
_sym_db.RegisterMessage(Curso)

CrudCurso = _reflection.GeneratedProtocolMessageType('CrudCurso', (_message.Message,), {
  'DESCRIPTOR' : _CRUDCURSO,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:CrudCurso)
  })
_sym_db.RegisterMessage(CrudCurso)

Aluno = _reflection.GeneratedProtocolMessageType('Aluno', (_message.Message,), {
  'DESCRIPTOR' : _ALUNO,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:Aluno)
  })
_sym_db.RegisterMessage(Aluno)

CrudAluno = _reflection.GeneratedProtocolMessageType('CrudAluno', (_message.Message,), {
  'DESCRIPTOR' : _CRUDALUNO,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:CrudAluno)
  })
_sym_db.RegisterMessage(CrudAluno)

AlunosReq = _reflection.GeneratedProtocolMessageType('AlunosReq', (_message.Message,), {
  'DESCRIPTOR' : _ALUNOSREQ,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:AlunosReq)
  })
_sym_db.RegisterMessage(AlunosReq)

AlunosRes = _reflection.GeneratedProtocolMessageType('AlunosRes', (_message.Message,), {
  'DESCRIPTOR' : _ALUNOSRES,
  '__module__' : 'rcp_pb2'
  # @@protoc_insertion_point(class_scope:AlunosRes)
  })
_sym_db.RegisterMessage(AlunosRes)

_SERVICES = DESCRIPTOR.services_by_name['Services']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\312\002\tApp\\Proto\342\002\025App\\Proto\\GPBMetadata'
  _MATRICULA._serialized_start=13
  _MATRICULA._serialized_end=121
  _CRUDMATRICULA._serialized_start=123
  _CRUDMATRICULA._serialized_end=200
  _DISCIPLINA._serialized_start=202
  _DISCIPLINA._serialized_end=282
  _CRUDDISCIPLINA._serialized_start=284
  _CRUDDISCIPLINA._serialized_end=347
  _CURSO._serialized_start=349
  _CURSO._serialized_end=386
  _CRUDCURSO._serialized_start=388
  _CRUDCURSO._serialized_end=436
  _ALUNO._serialized_start=438
  _ALUNO._serialized_end=507
  _CRUDALUNO._serialized_start=509
  _CRUDALUNO._serialized_end=557
  _ALUNOSREQ._serialized_start=559
  _ALUNOSREQ._serialized_end=625
  _ALUNOSRES._serialized_start=627
  _ALUNOSRES._serialized_end=679
  _SERVICES._serialized_start=682
  _SERVICES._serialized_end=885
# @@protoc_insertion_point(module_scope)
